## Intro to CSV & Pandas

**Tabular data**
- Tabular data consists of data stored in rows and columns
- rows are also called records, as they represent a single observation
- rows are usually identified by their index i.e. the row number
- columns are also called fields, as they represent a single attribute
- columns are usually identified by their labels i.e. the column name

**CSV format**
- CSV stands for comma-separated values.
- Its a common format for storing tabular data.
- In a csv file, we store tabular by storing:
    - each row in the table in a new line
    - each value in a row is separated by a commas

Example:
```csv
name,age,marks
angel,15,98
shreya,14,89
ahana,13,72
```

**Pandas**
- Pandas is a library/module for working with tabular data.
- It provides a special data type (called a DataFrame) for storing tabular data and supports tabular operations.
- We can directly load a csv file into a DataFrame using the `read_csv()` function of the pandas module

In [1]:
import pandas

table = pandas.read_csv("./assets/dataset.csv")
table

,index,species_ID,type_1,type_2,HP,phAtk,phDef,spAtk,spDef,speed,...,weight,catch_rate,base_exp,item_1,item_2,gender_ratio,egg_cycles,growth_rate,egg_group_1,egg_group_2
0,152,CHIKORITA,GRASS,...,40,50,65,50,65,45,...,140,45,64,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
1,153,BAYLEEF,GRASS,...,65,65,80,65,80,65,...,350,45,141,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
2,154,MEGANIUM,GRASS,FAIRY,80,80,110,75,110,75,...,2220,45,208,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,MONSTER,PLANT
3,155,CYNDAQUIL,FIRE,...,40,60,40,60,50,65,...,170,45,65,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
4,156,QUILAVA,FIRE,...,60,65,60,85,65,85,...,420,45,142,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,75,GRAVELER,ROCK,...,55,95,120,45,45,40,...,2320,120,134,NO_ITEM,EVERSTONE,F50,15,MEDIUM_SLOW,MINERAL,...
96,76,GOLEM,ROCK,...,80,105,160,50,65,40,...,6620,45,177,NO_ITEM,EVERSTONE,F50,15,MEDIUM_SLOW,MINERAL,...
97,92,GASTLY,GHOST,...,30,35,30,95,35,75,...,2,190,95,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
98,93,HAUNTER,GHOST,...,45,60,45,100,55,95,...,2,90,126,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
99,94,GENGAR,GHOST,...,60,85,60,110,75,110,...,890,45,190,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...

## Tabular Operations

---
- Checking the size of the table

    ```Python
    SYNTAX:
    rows, cols = table.shape
    ```

In [2]:
rows, cols = table.shape
print(f"Table has {rows} rows and {cols} columns")

Table has 100 rows and 24 columns

---
- Accessing a particular value *(given its row number and its column name)*

    ```Python
    SYNTAX:
    table.loc[ [row_number] , [column_name] ]
    ```

In [3]:
result = table.loc[ [3] , ['species_ID'] ]
result

  species_ID
3  CYNDAQUIL

---
- Accessing particular columns *(given column names)*
- The same syntax can also be used for rearranging or deleting the columns

    ```Python
    SYNTAX:
    table.loc[ : , [column_names] ]
    ```

In [4]:
result = table.loc[ : , ['species_ID', 'weight', 'height'] ]
result

   species_ID  weight  height
0   CHIKORITA     140     211
1     BAYLEEF     350     311
2    MEGANIUM    2220     511
3   CYNDAQUIL     170     108
4     QUILAVA     420     211
..        ...     ...     ...
95   GRAVELER    2320     303
96      GOLEM    6620     407
97     GASTLY       2     403
98    HAUNTER       2     503
99     GENGAR     890     411

[100 rows x 3 columns]

---
- Accessing a particular rows *(given row numbers)*

    ```Python
    SYNTAX:
    table.loc[ [row_numbers] , : ]
    ```

In [5]:
result = table.loc[ [3, 4, 5] , : ]
result

,index,species_ID,type_1,type_2,HP,phAtk,phDef,spAtk,spDef,speed,...,weight,catch_rate,base_exp,item_1,item_2,gender_ratio,egg_cycles,growth_rate,egg_group_1,egg_group_2
3,155,CYNDAQUIL,FIRE,...,40,60,40,60,50,65,...,170,45,65,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
4,156,QUILAVA,FIRE,...,60,65,60,85,65,85,...,420,45,142,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...
5,157,TYPHLOSION,FIRE,...,80,85,80,105,85,95,...,1750,45,209,NO_ITEM,...,F12_5,20,MEDIUM_SLOW,GROUND,...

---
- Accessing particular rows *(given a condition)*
- This process is also known as filtering the rows

    ```Python
    SYNTAX:
    table.loc[ (condition), : ]
    ```

In [6]:
result = table.loc[ (table['HP']>100) , : ]
result

,index,species_ID,type_1,type_2,HP,phAtk,phDef,spAtk,spDef,speed,...,weight,catch_rate,base_exp,item_1,item_2,gender_ratio,egg_cycles,growth_rate,egg_group_1,egg_group_2
12,164,NOCTOWL,FLYING,GHOST,110,50,50,80,110,70,...,900,90,162,NO_ITEM,...,F50,15,MEDIUM_FAST,FLYING,...
36,171,LANTURN,WATER,ELECTRIC,115,58,58,76,76,67,...,500,75,156,NO_ITEM,...,F50,20,SLOW,WATER_2,...
54,21,DOOMSPARCE,NORMAL,DRAGON,125,95,80,80,75,45,...,40,90,175,NO_ITEM,...,F50,20,MEDIUM_FAST,GROUND,...
60,115,KANGASKHAN,NORMAL,...,105,105,80,40,80,90,...,1760,45,175,NO_ITEM,...,F100,20,MEDIUM_FAST,MONSTER,...
83,39,JIGGLYPUFF,NORMAL,FAIRY,115,55,30,55,35,30,...,120,170,76,NO_ITEM,...,F75,10,FAST,FAIRY,...
84,40,WIGGLYTUFF,NORMAL,FAIRY,140,85,50,70,50,45,...,260,50,109,NO_ITEM,...,F75,10,FAST,FAIRY,...

---
- Rearranging rows *(based on column values)*
- This process is also known as sorting the rows

    ```Python
    SYNTAX:
    table.sort_values(['column_names'], ascending=[True/False])
    ```

In [7]:
result = table.sort_values(['HP'], ascending=[False])
result

,index,species_ID,type_1,type_2,HP,phAtk,phDef,spAtk,spDef,speed,...,weight,catch_rate,base_exp,item_1,item_2,gender_ratio,egg_cycles,growth_rate,egg_group_1,egg_group_2
84,40,WIGGLYTUFF,NORMAL,FAIRY,140,85,50,70,50,45,...,260,50,109,NO_ITEM,...,F75,10,FAST,FAIRY,...
54,21,DOOMSPARCE,NORMAL,DRAGON,125,95,80,80,75,45,...,40,90,175,NO_ITEM,...,F50,20,MEDIUM_FAST,GROUND,...
36,171,LANTURN,WATER,ELECTRIC,115,58,58,76,76,67,...,500,75,156,NO_ITEM,...,F50,20,SLOW,WATER_2,...
83,39,JIGGLYPUFF,NORMAL,FAIRY,115,55,30,55,35,30,...,120,170,76,NO_ITEM,...,F75,10,FAST,FAIRY,...
12,164,NOCTOWL,FLYING,GHOST,110,50,50,80,110,70,...,900,90,162,NO_ITEM,...,F50,15,MEDIUM_FAST,FLYING,...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88,63,ABRA,PSYCHIC,...,30,25,20,95,50,80,...,430,200,73,NO_ITEM,...,F25,20,MEDIUM_SLOW,HUMANSHAPE,...
97,92,GASTLY,GHOST,...,30,35,30,95,35,75,...,2,190,95,NO_ITEM,...,F50,20,MEDIUM_SLOW,INDETERMINATE,...
57,213,SHUCKLE,BUG,ROCK,25,5,250,5,250,5,...,450,190,80,BERRY,...,F50,20,MEDIUM_SLOW,BUG,...
15,172,PICHU,ELECTRIC,...,20,40,15,35,35,55,...,40,190,42,NO_ITEM,BERRY,F50,10,MEDIUM_FAST,NONE,...
55,50,DIGLETT,GROUND,...,10,55,25,30,40,90,...,20,255,81,NO_ITEM,...,F50,20,MEDIUM_FAST,GROUND,...

---
- Aggregate operations *(column wise)*
- This only works on numeric columns

    ```Python
    SYNTAX:
    table.describe()
    ```

In [8]:
result = table.describe()
result

,index,HP,phAtk,phDef,spAtk,spDef,speed,BST,height,weight,catch_rate,base_exp,egg_cycles
count,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,112.670000,64.600000,66.580000,65.630000,63.96000,66.960000,60.020000,387.750000,289.540000,688.640000,123.200000,122.230000,18.300000
std,64.631052,24.429656,24.427663,32.669034,26.07058,28.790753,28.431019,99.846789,174.559267,883.058866,77.366764,50.956281,4.096069
min,15.000000,10.000000,5.000000,15.000000,5.00000,20.000000,5.000000,200.000000,8.000000,2.000000,25.000000,37.000000,10.000000
25%,49.250000,45.000000,50.000000,45.000000,45.00000,48.750000,40.000000,300.000000,200.000000,147.500000,45.000000,74.750000,15.000000
50%,100.500000,62.500000,65.000000,60.000000,60.00000,65.000000,55.000000,400.000000,257.000000,425.000000,90.000000,125.000000,20.000000
75%,172.250000,80.000000,85.000000,80.000000,80.00000,80.000000,80.000000,476.250000,407.000000,882.500000,190.000000,164.250000,20.000000
max,233.000000,140.000000,130.000000,250.000000,140.00000,250.000000,140.000000,540.000000,1106.000000,6620.000000,255.000000,230.000000,40.000000

## Homework

Write queries to find the following insights from the given dataset:
1. What Pokemon has the highest speed stat
2. How many pokemon has an HP stat of over 100
3. Sort pokemon based on their names in alphabetic order (A to Z)

In [12]:
result = table.sort_values(['speed'], ascending=[False]).reset_index(drop=True)
result.loc[0, 'species_ID']

'DUGTRIO'

In [14]:
result = table.loc[ (table['HP']>100) , : ]
result.shape[0]

6

In [3]:
result = table.sort_values(['species_ID'], ascending=[True])
result

,index,species_ID,type_1,type_2,HP,phAtk,phDef,spAtk,spDef,speed,...,weight,catch_rate,base_exp,item_1,item_2,gender_ratio,egg_cycles,growth_rate,egg_group_1,egg_group_2
88,63,ABRA,PSYCHIC,...,30,25,20,95,50,80,...,430,200,73,NO_ITEM,...,F25,20,MEDIUM_SLOW,HUMANSHAPE,...
90,65,ALAKAZAM,PSYCHIC,...,55,50,45,140,85,125,...,1060,50,186,NO_ITEM,...,F25,20,MEDIUM_SLOW,HUMANSHAPE,...
41,181,AMPHAROS,ELECTRIC,DRAGON,95,80,80,125,100,60,...,1360,45,194,NO_ITEM,...,F50,20,MEDIUM_SLOW,MONSTER,GROUND
34,24,ARBOK,POISON,DRAGON,60,90,75,65,70,90,...,1430,90,147,NO_ITEM,...,F50,20,MEDIUM_FAST,GROUND,DRAGON
24,168,ARIADOS,BUG,POISON,90,100,80,60,80,40,...,740,90,134,NO_ITEM,...,F50,15,FAST,BUG,...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31,70,WEEPINBELL,GRASS,POISON,65,95,50,90,45,55,...,140,120,151,NO_ITEM,...,F50,20,MEDIUM_SLOW,PLANT,...
84,40,WIGGLYTUFF,NORMAL,FAIRY,140,85,50,70,50,45,...,260,50,109,NO_ITEM,...,F75,10,FAST,FAIRY,...
37,194,WOOPER,WATER,GROUND,60,50,55,35,30,20,...,190,255,52,NO_ITEM,...,F50,20,MEDIUM_FAST,WATER_1,GROUND
14,178,XATU,FLYING,PSYCHIC,65,60,55,115,70,105,...,330,75,171,NO_ITEM,...,F50,20,MEDIUM_FAST,FLYING,...
27,41,ZUBAT,POISON,FLYING,40,45,35,25,40,55,...,170,255,54,NO_ITEM,...,F50,15,MEDIUM_FAST,FLYING,...